<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter
 */
function librarian_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
	if (in_array($form_id, ['node_book_form', 'node_book_edit_form'])) {
		_librarian_bookeditform($form);
	} else if ($form_id == 'node_loan_form') {
		// dpr($form);
		$form['title']['widget'][0]['value']['#default_value'] = 'Loan: ' . date('Y-m-d H:i', time());
	}
}

function _librarian_bookeditform(&$form)
{
	$form['#attached']['library'][] = 'librarian/librarian';
	$form['cover_url'] = [
		'#type' => 'hidden',
	];

	$form['scanner'] = [
		'#type' => 'inline_template',
		'#template' => '<div id="lookup-controls">
							<div id="scan-controls"><div>
								<a class="button" id="startButton">Scan</a>
								<a class="button" id="resetButton">Stop</a>
							</div>

							<div>
								<video id="video" width="300" height="200" style="border: 1px solid gray"></video>
							</div>

							<div id="sourceSelectPanel" style="display:none">
								<label for="sourceSelect">Change video source:</label>
								<select id="sourceSelect" style="max-width:400px">
								</select>
							</div>
						</div>
					
						<div id="cover-display">
							<p>Please select the best cover image</p>
							<div id="cover-images">
								<img id="cover-image-0" src=""/>
								<img id="cover-image-1" src=""/>
							</div>
						</div>
						</div>',
	];
}

/**
 * Things that have to be done when certain types of content are saved
 * 
 * @param Drupal\Core\Entity\EntityInterface $entity
 * @return void
 */
function librarian_entity_presave(Drupal\Core\Entity\EntityInterface $entity)
{
	$s = \Drupal::service('librarian_service.library');

	switch ($entity->bundle()) {
		case 'book':
			// When a Book is saved, we may need to get the cover image and download it to the local filesystem
			$s->saveBook($entity);
			break;
	}
}
